spring:
  datasource:
    url: ${AZURE_POSTGRESQL_URL}
    username: ${AZURE_POSTGRESQL_USERNAME}
    password: ${AZURE_POSTGRESQL_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_JWT_ISSUER_URI}
          jwk-set-uri: ${AZURE_JWT_PROTOCOL_URI}

jwt:
  auth:
    converter:
      resource-id: ${JWT_RESOURCE_ID}
      principal-attribute: ${JWT_PRINCIPAL_ATTRIBUTE}