server:
  tomcat:
    accesslog:
      enabled: true

logging:
  pattern:
    file: "%white(%d{ISO8601}) %highlight(%-5level) [%cyan(%t)] %yellow(%C{1}): %msg%n%throwable"
    console: "%white(%d{ISO8601}) %highlight(%-5level) [%cyan(%t)] %yellow(%C{1}): %msg%n%throwable"
  file:
    path: /usr/local/tomcat/logs
    name: logs/backend-service.log
  level:
    nl.optifit.backendservice: debug
